using ECommerce.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ECommerce.Infrastructure.Configurations;

public sealed class ProductImageConfiguration : IEntityTypeConfiguration<ProductImage>
{
    public void Configure(EntityTypeBuilder<ProductImage> builder)
    {
        builder.HasKey(i => i.Id);

        // Guid is generated by the entity constructor — not by the DB
        builder.Property(i => i.Id)
            .ValueGeneratedNever();

        builder.Property(i => i.ImageUrl)
            .IsRequired()
            .HasMaxLength(2048);

        builder.Property(i => i.CloudinaryPublicId)
            .IsRequired()
            .HasMaxLength(500)
            .HasDefaultValue(string.Empty);

        builder.Property(i => i.AltText)
            .HasMaxLength(200);

        builder.Property(i => i.DisplayOrder)
            .HasDefaultValue(0);

        builder.Property(i => i.IsMain)
            .HasDefaultValue(false);

        // No CreatedAt / UpdatedAt — ProductImage is not an auditable entity

        // ── Indexes ───────────────────────────────────────────────────────────
        builder.HasIndex(i => i.ProductId)
            .HasDatabaseName("IX_ProductImage_ProductId");

        builder.HasIndex(i => new { i.ProductId, i.DisplayOrder })
            .HasDatabaseName("IX_ProductImage_ProductId_DisplayOrder");

        builder.ToTable("ProductImages");
    }
}
